apiVersion: v1
entries:
  easyhaproxy:
  - apiVersion: v2
    appVersion: 6.0.1
    created: "2026-02-23T02:07:13.010419645Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 8f07702f59ade6f652effb047f24ea7ec33cb7e44f06d51c096fc996cc90955f
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v2
    appVersion: 6.0.0
    created: "2026-02-23T02:07:13.009466628Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: d95d3bbf33c938d6fd9475a3f5af498211d991cc9a48270a44544766a5f6a238
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 5.0.0
    created: "2026-02-23T02:07:13.009068686Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: ee10f566832d39d7eec7f245ef3ec42110bd5bc29aafc228b35f9d3e7719930e
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 4.6.0
    created: "2026-02-23T02:07:13.008691313Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: ab947eff1087e33745dca8f14d5423080caa09fc0ba5cebf0c637ba57b57b362
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 4.5.0
    created: "2026-02-23T02:07:13.008327655Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 6e68e1e7b31acb9e1eb144b94dcabb9eeef8e3f44d18ca0850e532dcf5126a49
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2026-02-23T02:07:13.007935674Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 29f3cca7d91523438feeefff91dac0a81bfff2f1494b52db3550ccf30fbb636c
    icon: https://opensource.byjg.com/img/easy_haproxy_logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 4.3.1-rc1
    created: "2026-02-23T02:07:13.007341987Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 585ff193a79065e2a8680bb10dda2631c92a22e2f3c8332f8e319453dfaae8d2
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 4.3.0
    created: "2026-02-23T02:07:13.006965495Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 3d36cdb187b11bb71667286593f0f58da93312c59fbc27ff166b7d8e7921412c
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 4.2.0
    created: "2026-02-23T02:07:13.006634077Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 2f2ef5dba014e2e308ea7b1d7034a43b214839449dddcbedc04933d8fe1f77a4
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: master
    created: "2026-02-23T02:07:13.006299573Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a111f02e52ff8b1c8be11f32c5a5ed43ad7f3cb6108d74de296a774e3dbc28a0
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: test
    created: "2026-02-23T02:07:13.005915858Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a5dee1fe1c339cb4916fc076657db77957d12a2c87279acab1fded1501196e87
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: test
    created: "2026-02-23T02:07:13.005564673Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: e2019a2ec047d4289cabe25b7556b74411689e1612505a787ddd6c6d7730ce53
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: test
    created: "2026-02-23T02:07:13.005233936Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: fcdf99bf482fd2830f1a6de441aa8d5d7dfc973633a035c063ad9a1bf9bb9f93
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.0.tgz
    version: 0.1.0
  static-httpserver:
  - apiVersion: v2
    appVersion: latest
    created: "2026-02-23T02:07:13.011231316Z"
    description: A minimal HTTP server for static pages. Full version with "parking"
      HTML.
    digest: ef8be684aa3853ce7c3801f110d22cec832ca8f589d662d72ae63416ada2ec08
    name: static-httpserver
    type: application
    urls:
    - https://opensource.byjg.com/helm/static-httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-23T02:07:13.004760624Z"
